document.write('<body class="dark-mode" background="https://images.rbxcdn.com/782b7fc18a24ee997efd9a7f02fa4bf9-bg_08072019.jpg">');
document.write('    <nav class="nav">');
document.write('        <div class="left-nav">');
document.write('            <img src="https://totallynottg.github.io/corp.tgblox/l/img/text-1669918561590.png" class="logo" title="Ollieblox">');
document.write('        </div>');
document.write('    </nav>');
document.write('    <div class="main-content">');
document.write('        <section class="darken">');
document.write('            <div class="select-card light-mode">');
document.write('                <h2 class="bold-font" id="disappear" style="text-align: center;">Buy a Card</h2>');
document.write('                <button class="pick" id="card-button">Pick a Card</button>');
document.write('                <div class="select-which-card" id="popup" style="border-top: 0.5px solid black;">');
document.write('                    <h1 class="bold-font" style="text-align:center;">Which Card Do you Want?</h1>');
document.write('                    <div>');
document.write('                        <h1 class="bold-font" style="text-align: center;">Digital Card</h1>');
document.write('                        <p class="normal-font" style="text-align: center;">Send Giftcard On Email or Printing.</p>');
document.write('                        <button class="pick">Choose</button>');
document.write('                        <h1 class="bold-font" style="text-align: center;">Physical Card</h1>');
document.write('                        <p class="normal-font" style="text-align: center;">Get a Card Online or from a Nearby Guinea-Store.</p>');
document.write('                        <a href="https://my-store-de0b5d.creator-spring.com"><button class="pick">Choose</button></a>');
document.write('                    </div>');
document.write('                </div>');
document.write('                <p class="normal-font" style="text-align: center;width: 200px;margin-left: auto;margin-right: auto;">By buying this card, you are Accepting the <a href="https://totallynottg.github.io/en.help.tgblox/terms/terms-of-service" style="color:black;">Terms of Service</a> From Ollieblox.</p>');
document.write('            </div>');
document.write('        </section>');
document.write('    </div>');
document.write('');
document.write('</body>');
